name: CI pipeline
on: 
  pull_request:

env:
  solution: CSC8503.sln
  buildPlatform: x64
  buildConfiguration: Debug
  buildArgs: '/t:Clean,Build'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: echo "building..."
      - run: msbuild "$Solution" /p:Platform=$buildPlatform $buildArgs
