name: CI pipeline
on: 
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SolutionPath: CSC8503.sln

jobs:
  build:
    env:
      buildPlatform: x64  
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - name: PC build
        run: msbuild "$env:SolutionPath" /t:Rebuild /p:Platform=$env:BuildPlatform