name: CI pipeline
on: 
  pull_request:
    types: [opened, synchronize, reopened]

env:
  RepositoryUrl: 'https://github.com/${{ github.repository }}'
  RepositoryBranch: '${{ github.ref }}'
  Configuration: Release
  SolutionPath: CSC8503.sln
  buildPlatform: x64
  buildArgs: '/t:Clean,Build'

jobs:
  build:
  runs-on: windows-latest
  steps:
  - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
  - name: Build extension
      run: msbuild $env:SolutionPath /t:Rebuild /p:Platform=$BuildPlatform