name: CI pipeline
on: 
  pull_request:

env:
  solution: CSC8503.sln
  buildPlatform: x64
  buildConfiguration: Debug
  buildArgs: '/t:Clean,Build'
  msbuild: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: echo building...
    - run: "$msbuild" "$Solution" /p:Platform="$buildPlatform" "$buildArgs"