name: CI pipeline
on: 
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SolutionPath: CSC8503.sln
  buildPlatform: x64  
  buildArgs: '/t:Clean,Build'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - name: PC build
        run: msbuild "$SolutionPath" /t:Rebuild /p:Platform=$BuildPlatform